### ISSUE TITLE
Can you add custom cache directory settings?

### ISSUE THREAD

**Issue by sanqi** [wonday/react-native-image-cache-wrapper#1]
There are very few parameters that can be customized at the moment. Can you add this?

**Comment by wonday** [comment]
Where do you want to save?
and why do you want add it?

**Comment by abhijeetskadam** [comment]
+1
@wonday thank you for such a tiny and nice library.
I need to show images from my app to the Gallery as well, same like whats app.

**Comment by wonday** [comment]
I have published a property of ```CachedImage.cacheDir```, you can get/set it.
