### ISSUE TITLE
clear cache will cleared code-push bundle 

### ISSUE THREAD

**Issue by Yunnathai** [wonday/react-native-image-cache-wrapper#2]
Can clearing the cache not only clear the image cache?
it will clear the code-push update bundle package now，
also clear assets/image too。

**Comment by wonday** [comment]
clear cache just remove the ```RNFetchBlob.fs.dirs.CacheDir + "/CachedImage/";``` a folder under cache.
this folder was created by this js.
How do you use it? can you give me your codes?
